name: Android CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:

  build:
    name: Test Build and Release
    runs-on: ubuntu-latest
    env:
      BRANCH_NAME: ${{ github.ref || github.head_ref }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set gradle.properties
        run: echo " ${{ secrets.GRADLE_PROPERTIES }} " >> gradle.properties

      - name: Create google-services.json file
        run: cat androidApp/google-services.json | base64

      - name: Putting data in google-services.json
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA > androidApp/google-services.json

      - name: KT lint check
        run: ./gradlew ktlintFormat --info --stacktrace

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit test cases
        run: ./gradlew testDebugUnitTest

      - name: Build Android Release
        run: ./gradlew assembleRelease

      - name: Install Firebase Tools
        run: sudo npm install -g firebase-tools

      - id: 'auth'
        name: 'Authenticate with Firebase'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

      - name: Distribute APK to Firebase App Distribution
        run: firebase appdistribution:distribute androidApp/build/outputs/apk/release/androidApp-release-unsigned.apk
          --app ${{ secrets.FIREBASE_APP_ID }}
          --release-notes "{{ env.BRANCH_NAME }}"
          --groups testers
          --debug


